### 1. 

En el archivo "logistic_regression_df_class" hemos visto un ejemplo multiclase. Elimina del dataframe todas las filas que se correspondan con la clase valor "1".

Ahora, realiza el ejercicio con el nuevo dataframe:

- ¿Se mejora la precisión del algoritmo con dos clases? ¿por qué?

LogisticRegression() es una clase que tiene varios parámetros de entrada. Investiga (modifica, prueba) los argumentos y comenta si modificando algunas de ellas se mejora el porcentaje de acierto del problema.

https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html


In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from sklearn import model_selection
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import mean_absolute_error, mean_squared_error
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [4]:
df = pd.read_csv("../data/usuarios_win_mac_lin.csv")
df = df[df['clase'] != 1]
df

duracion  paginas  acciones  valor  clase
0         7.0        2         4      8      2
1        21.0        2         6      6      2
2        57.0        2         4      4      2
3       101.0        3         6     12      2
4       109.0        2         6     12      2
..        ...      ...       ...    ...    ...
165      13.0        1         7     42      0
166      12.0        1         2      6      0
167      13.0        1         3      9      0
168      13.0        1         7     28      0
169      12.0        1         6     18      0

[130 rows x 5 columns]

In [5]:
# Vemos distribucion de columna clase
df.groupby('clase').count()

duracion  paginas  acciones  valor
clase                                    
0            86       86        86     86
2            44       44        44     44

In [6]:
# Defining X and Y Variables
X = np.array(df.drop(['clase'], 1))
y = np.array(df['clase'])
X.shape

(130, 4)

In [22]:
# Splitting Data into training and test sets
X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y, test_size=0.2, random_state=13)

In [23]:
model = linear_model.LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [24]:
predictions = model.predict(X_test)
print(predictions)

[0 0 0 0 0 0 0 2 0 0 2 0 0 0 2 2 2 2 0 0 0 2 0 0 0 2]


In [25]:
# Score of our prediction
model.score(X_train, y_train)

0.9519230769230769

In [26]:
# Confusion Matrix
confusion_matrix(y_test, predictions)

array([[18,  1],
       [ 0,  7]])

Los resultados mejoran un monton respecto a la clasificacion sin quitar la clase 1, todo esta predicho de manera correcta salvo un dato. Esto puede ser porque la clase 1 introducia mas errores a la prediccion y las diferencias estan mejor marcadas sin esa clase.

Tenemos un score de 0.95 del modelo con respecto a un 0.85 en el ejemplo de clase y una matriz de confusion de:


In [ ]:
[[18,  1]
[ 0,  7]]
       

 indicando que solo se ha clasificado erroneamente en uno de los datos con 
             
 respecto a la clasificacion del ejemplo en el que la matriz de confusion es:

In [ ]:
[[16  0  2]
[ 3  3  0]
[ 0  0 10]]


 donde se equivoca el algoritmo en hasta 5 ocasiones, dicho eso la prediccion inicial no es mala en absoluto.
 Tambien se pueden parametros como el seed y test_size que nos pueden albergar resultados diferentes.