### 1. 

En el archivo "logistic_regression_digits" hemos visto un ejemplo multiclase. Elimina todas las imágenes y etiqueta (label) cuyo valor del label no sea 1 o 9. Es decir, elimina todos los dígitos y quédate solo con los dígitos 1 y 9.

Ahora, realiza un entrenamiento con logistic regression con los nuevos datos:

- ¿Se mejora la precisión del algoritmo con dos clases? ¿por qué?

LogisticRegression() es una clase que tiene varios parámetros de entrada. Investiga (modifica, prueba) los argumentos y comenta si modificando algunas de ellas se mejora el porcentaje de acierto del problema.

https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html

In [174]:
# Libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
import sklearn.metrics as metrics


In [175]:
# Loading Data
digits = load_digits() # 8x8 = 64 pixels  -- Very clean Dataset 

In [176]:
# Loading data into dataframe with pixel values as first 64 columns and target as column 65
df = pd.DataFrame(data= np.c_[digits['data'], digits['target']])
df

0    1     2     3     4     5    6    7    8    9   ...   55   56  \
0     0.0  0.0   5.0  13.0   9.0   1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
1     0.0  0.0   0.0  12.0  13.0   5.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
2     0.0  0.0   0.0   4.0  15.0  12.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
3     0.0  0.0   7.0  15.0  13.0   1.0  0.0  0.0  0.0  8.0  ...  0.0  0.0   
4     0.0  0.0   0.0   1.0  11.0   0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
...   ...  ...   ...   ...   ...   ...  ...  ...  ...  ...  ...  ...  ...   
1792  0.0  0.0   4.0  10.0  13.0   6.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
1793  0.0  0.0   6.0  16.0  13.0  11.0  1.0  0.0  0.0  0.0  ...  0.0  0.0   
1794  0.0  0.0   1.0  11.0  15.0   1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
1795  0.0  0.0   2.0  10.0   7.0   0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
1796  0.0  0.0  10.0  14.0   8.0   1.0  0.0  0.0  0.0  2.0  ...  0.0  0.0   

       57   58    59    60    61   62   63   64  
0     0.0  6.0  13.0  10.0   0.0  0.0  0.0  0.0  
1     0.0  0.0  11.0  16.0  10.0  0.0  0.0  1.0  
2     0.0  0.0   3.0  11.0  16.0  9.0  0.0  2.0  
3     0.0  7.0  13.0  13.0   9.0  0.0  0.0  3.0  
4     0.0  0.0   2.0  16.0   4.0  0.0  0.0  4.0  
...   ...  ...   ...   ...   ...  ...  ...  ...  
1792  0.0  2.0  14.0  15.0   9.0  0.0  0.0  9.0  
1793  0.0  6.0  16.0  14.0   6.0  0.0  0.0  0.0  
1794  0.0  2.0   9.0  13.0   6.0  0.0  0.0  8.0  
1795  0.0  5.0  12.0  16.0  12.0  0.0  0.0  9.0  
1796  1.0  8.0  12.0  14.0  12.0  1.0  0.0  8.0  

[1797 rows x 65 columns]

In [177]:
# Filtering the dataframe
df = df[(df[64] == 1) | (df[64] == 9)]
df

0    1     2     3     4     5    6    7    8    9   ...   55   56  \
1     0.0  0.0   0.0  12.0  13.0   5.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
9     0.0  0.0  11.0  12.0   0.0   0.0  0.0  0.0  0.0  2.0  ...  0.0  0.0   
11    0.0  0.0   0.0   0.0  14.0  13.0  1.0  0.0  0.0  0.0  ...  0.0  0.0   
19    0.0  0.0   6.0  14.0   4.0   0.0  0.0  0.0  0.0  0.0  ...  2.0  0.0   
21    0.0  0.0   0.0   2.0  16.0  16.0  2.0  0.0  0.0  0.0  ...  0.0  0.0   
...   ...  ...   ...   ...   ...   ...  ...  ...  ...  ...  ...  ...  ...   
1772  0.0  0.0   5.0  14.0  11.0   8.0  0.0  0.0  0.0  4.0  ...  0.0  0.0   
1774  0.0  0.0   6.0  12.0  12.0   6.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
1786  0.0  0.0   4.0  14.0  15.0   6.0  0.0  0.0  0.0  5.0  ...  0.0  0.0   
1792  0.0  0.0   4.0  10.0  13.0   6.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
1795  0.0  0.0   2.0  10.0   7.0   0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   

       57   58    59    60    61    62   63   64  
1     0.0  0.0  11.0  16.0  10.0   0.0  0.0  1.0  
9     0.0  9.0  12.0  13.0   3.0   0.0  0.0  9.0  
11    0.0  0.0   1.0  13.0  16.0   1.0  0.0  1.0  
19    0.0  7.0  16.0  16.0  13.0  11.0  1.0  9.0  
21    0.0  0.0   2.0  12.0  15.0   4.0  0.0  1.0  
...   ...  ...   ...   ...   ...   ...  ...  ...  
1772  0.0  7.0  15.0  12.0   5.0   0.0  0.0  9.0  
1774  0.0  2.0  11.0  10.0   4.0   0.0  0.0  1.0  
1786  0.0  4.0  13.0  15.0   9.0   0.0  0.0  9.0  
1792  0.0  2.0  14.0  15.0   9.0   0.0  0.0  9.0  
1795  0.0  5.0  12.0  16.0  12.0   0.0  0.0  9.0  

[362 rows x 65 columns]

In [178]:
# Splitting the Data
X_train, X_test, y_train, y_test = train_test_split(df.loc[:, :63], df.loc[:, 64], test_size=0.25, random_state=12)


In [179]:
# Checking sizes of data sets
print('X_train shape:', X_train.shape)
print('y_train shape:', y_train.shape)
print('X_test shape:', X_test.shape)
print('y_test shape:', y_test.shape)

X_train shape: (271, 64)
y_train shape: (271,)
X_test shape: (91, 64)
y_test shape: (91,)


In [180]:
# Default parameters of a logistic regression
LogisticRegression(penalty='l2', dual=False, tol=0.0001, C=1.0, fit_intercept=True, intercept_scaling=1, class_weight=None, random_state=None, solver='lbfgs', max_iter=100, multi_class='auto', verbose=0, warm_start=False, n_jobs=None, l1_ratio=None)

LogisticRegression()

In [181]:
# Creating a logistic regression model and fittting it to our training data

logisticRegr = LogisticRegression(penalty='l2', dual=False, tol=0.0001, C=1.0, fit_intercept=True, intercept_scaling=1, class_weight=None, random_state=144, solver='lbfgs', max_iter=10, multi_class='auto', verbose=0, warm_start=False, n_jobs=None, l1_ratio=None)
logisticRegr.fit(X_train, y_train)

LogisticRegression(max_iter=10, random_state=144)

In [182]:
# Predictions of our model to our test data
y_pred = logisticRegr.predict(X_test)
y_pred

array([9., 1., 1., 9., 9., 9., 9., 9., 9., 9., 9., 9., 1., 1., 9., 1., 9.,
       1., 1., 9., 1., 1., 1., 9., 9., 9., 1., 9., 9., 9., 1., 1., 1., 9.,
       9., 1., 9., 9., 1., 9., 1., 9., 1., 9., 1., 1., 1., 1., 1., 1., 9.,
       9., 1., 1., 1., 1., 1., 9., 9., 9., 1., 1., 9., 9., 9., 9., 9., 9.,
       9., 1., 1., 9., 1., 9., 9., 1., 1., 1., 1., 1., 9., 1., 1., 9., 1.,
       1., 9., 1., 1., 1., 9.])

In [183]:
# Probablities of each classification in each class, we only have 2 classes therefore we have 2 columns
logisticRegr.predict_proba(X_test[:1])

array([[0.00162144, 0.99837856]])

In [184]:
# Possible classes
logisticRegr.classes_

array([1., 9.])

In [185]:
# Model Score
score = logisticRegr.score(X_test, y_test)
print('Score:', score * 100, "%")

Score: 98.9010989010989 %


In [186]:
# Confusion Matrix
cm = metrics.confusion_matrix(y_test, y_pred)
print(cm)

[[45  0]
 [ 1 45]]


La clasificacion mejora mucho usando solo 2 clases (score por encima de 97%) porque estamos limitando mucho las opciones y los datos de entrenamiento son suficientemente buenos y abundantes para realizar la distincion, observamos en la matrix de confusion que el algoritmo solo clasifica erroneamente imagenes

Alteracion de parametros de Logistic Regression: 
- reduciendo max_iter a 10 en vez de 100 nos sube el score de un 97% a un 98%
- haciendo la tolerancia 0.01 en vez de 0.0001 no cambia nada
- Con n_jobs = -1 no ha habido diferencia
- con verbose = 10 no cambia, verbose = 1 no cambia
- random_State = 1 no ha cambiado, random_State= 15 no ha cambiado, random_State = 144 no ha cambiado